fix: signin.tsx 파일 관련 에러 사항 해결 및 파일 이동
part4-1st-team/coworkers pull request #101
Opened 2024-09-20 06:18 UTC by ohjohwan

## 😎 담당자

> 든든한~ 오조환

ㅤ

## 🧩 이슈 번호

> #16 

ㅤ

## ✨ 작업 내용

> 작업한 내용을 설명해주세요

- fix: input 컴포넌트에 forwardRef 추가해 control에서 발생하는 에러 해결
-  fix: input 컴포넌트 default props 삭제
- refactor: 로그인, 회원가입 기능 파일 containers -> user로 이동
- fix: 리다이렉트 주소 중 index 부분 삭제

ㅤ

## 💡 이번 pr을 올리기 전에 받은 피드백이 있나요? (있으면 체크리스트 작성)

- [x] 수정한 피드백
- [ ] 수정 안 한 피드백

ㅤ

## 📸 스크린샷 또는 GIF

> ui 컴포넌트 개발, 페이지 퍼블리싱을 했다면 스크린샷도 올려주세요

ㅤ

## ✍🏻 참고사항

> 팀원들이 참고해야할 부분이 있다면 적어주세요

ㅤ

---

### 코드 리뷰 남길때 참고용 (pr 작성할 때 지우지 말기)

#### P1: 꼭 반영해주세요 (Request changes) - 리뷰어는 PR의 내용이 서비스에 중대한 오류를 발생할 수 있는 가능성을 잠재하고 있는 등 중대한 코드 수정이 반드시 필요하다고 판단되는 경우, P1 태그를 통해 리뷰 요청자에게 수정을 요청합니다. 리뷰 요청자는 p1 태그에 대해 리뷰어의 요청을 반영하거나, 반영할 수 없는 합리적인 의견을 통해 리뷰어를 설득할 수 있어야 합니다.

#### P2: 적극적으로 고려해주세요 (Request changes) - P2에 대해 수용하거나 만약 수용할 수 없는 상황이라면 적합한 의견을 들어 토론할 것을 권장합니다.

#### P3: 웬만하면 반영해 주세요 (Comment) - P3에 대해 수용하거나 만약 수용할 수 없는 상황이라면 반영할 수 없는 이유를 들어 설명하거나 다음에 반영할 계획을 명시적으로 표현합니다.

#### P4: 반영해도 좋고 넘어가도 좋습니다 (Approve) - 해당 의견을 반영하는 게 좋을지 고민해 보는 정도면 충분합니다

#### P5: 그냥 사소한 의견입니다 (Approve) - 아무런 의견을 달지 않고 무시해도 괜찮습니다

#### PQ: 질문입니다 (Question) - 질문에는 꼭 답을 해주세요

2024-09-20 06:24 UTC, mxkxx1011 requested changes

2024-09-20 06:24 UTC, mxkxx1011 commented on src/containers/user/oauth/kakao.tsx
> +          console.log('카카오 Access Token:', kakaoAccessToken);
p1) 콘솔 지워주세요

2024-09-20 06:24 UTC, mxkxx1011 commented on src/containers/user/oauth/kakao.tsx
> +const REDIRECT_URI = 'http://localhost:3000/oauth/kakao'; // 카카오 로그인 후 리디렉션될 URI
p1) 환경 변수 처리 하고 올려주세요

2024-09-20 06:24 UTC, mxkxx1011 commented on src/containers/user/oauth/kakao.tsx
> +            `https://fe-project-cowokers.vercel.app/7-1/auth/signIn/kakao`,
p1) axios instance 사용해주세요

2024-09-20 06:24 UTC, mxkxx1011 commented on src/containers/user/oauth/kakao.tsx
> +      const { code } = router.query;
pq) code가 어떤 쿼리 파라미터인가요?

2024-09-20 06:31 UTC, ohjohwan commented on src/containers/user/oauth/kakao.tsx
> +      const { code } = router.query;
카카오 플랫폼으로 로그인 후 리디렉션 될 때 리디렉션 URL 뒤에 인증 코드가 발급됩니다.

해당 코드를 리액트 쿼리로 추출한 겁니다.

결론 : code = 인증 코드(Authorization Code)

2024-09-20 07:57 UTC, mxkxx1011 commented on src/containers/user/oauth/kakao.tsx
>              `https://kauth.kakao.com/oauth/token`,
pq) axios 따로 써야 될거같은데 아닌가요?? 여기서는 일반 axios 함수 / 밑에서는 axios 인스턴스

2024-09-20 08:10 UTC, ohjohwan commented on src/containers/user/oauth/kakao.tsx
>              `https://kauth.kakao.com/oauth/token`,
axios에 baseURL이 설정되어 있어도 절대 경로를 설정하면 baseURL을 무시하고 절대 경로를 처리합니다. 따라서  axios를 따로 사용하지 않아도 괜찮습니다.

2024-09-21 04:41 UTC, mxkxx1011 approved these changes
userStore 나 쿠키 설정 잘 해주신 거 같아요! 사용은 안 해봤지만 기능 잘 될 거 같아요 ㅋㅋㅋ

2024-09-21 04:41 UTC, mxkxx1011 commented on src/pages/oauth/kakao.tsx
> +const STATE = 'someRandomState'; // 상태를 임의로 지정
pq) 백엔드에 토큰 전송할때 쓰이는 상태인건 알겠는데 왜 쓰이는 변수인가요 ??

2024-09-21 04:43 UTC, ohjohwan commented on src/pages/oauth/kakao.tsx
> +const STATE = 'someRandomState'; // 상태를 임의로 지정
저 state 값은 주강사님도 잘 모르시겠다고 하셔서 매니저님께 여쭤봐야 하는 부분입니다! 그래서 임의로 지정해뒀습니다!

2024-09-21 05:05 UTC, merged